apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cluster.yaml
- control-plane.yaml
- worker-node-pool.yaml

namespace: cluster-api-quickstart

patches:
- target:
    kind: AWSMachine
  patch: |-
    - op: replace
      path: /spec/sshKeyName
      value: cluster-api-quickstart
- target:
    kind: AWSCluster
  patch: |-
    - op: replace
      path: /spec/sshKeyName
      value: cluster-api-quickstart
- target:
    kind: AWSMachineTemplate
  patch: |-
    - op: replace
      path: /spec/template/spec/sshKeyName
      value: cluster-api-quickstart

commonLabels:
  cluster.x-k8s.io/cluster-name: "cluster-api-quickstart"
