apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- cluster.yaml
- control-plane.yaml
- worker-node-pool.yaml
namespace: cluster-quickstart
patches:
- target:
    kind: AWSMachine
  path: patches/ssh-key-name.yaml
- target:
    kind: AWSCluster
  path: patches/ssh-key-name.yaml
- target:
    kind: AWSMachineTemplate
  path: patches/ssh-key-name-in-template.yaml
commonLabels:
  cluster.x-k8s.io/cluster-name: "cluster-api-quickstart"
